// actionTypes.js
export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
export const UPDATE_LOCATION_INFO = 'UPDATE_LOCATION_INFO';
export const UPDATE_GUARDIAN_INFO = 'UPDATE_GUARDIAN_INFO';
export const UPDATE_VISITOR_INFO = 'UPDATE_VISITOR_INFO';
export const UPDATE_CNIC_FRONT = 'UPDATE_CNIC_FRONT';
export const UPDATE_CNIC_BACK = 'UPDATE_CNIC_BACK';
